language: go
sudo: false
before_script:
  - export TZ=America/Sao_Paulo
env:
  matrix:
  - GOPATH=$TRAVIS_BUILD_DIR/gosrc
  global:
  - GH_REF: github.com/timulato/website.git
  - secure: PRDjjlG41uszlPHIo9USkVLKmZj1udew77DgTmjIE5QSjHCe/bGEP3VhZ4t54sGmdzukUbK5lULCKdzYydrC//IMG4BbtiKxyjsdmK9fl2S7Ow3z9FwIDKW5xx9bS9NlizHOtJBI8LzGo76dGjJZ5JCrOAKqCZaG3uy47J5W0eHozKPkxahd4E3gJdK3n6vu6TqHn1fbBuK/exIRXV/S16wPkEkUCKTAyjGpzh7hwo9UkBliYqoYbt1Pr9zyS96wpobUPfLjN8z2uSl2Ixlb31C6xGEo6Qp0osuOR3230Of0vHMCSIkN2citGOBrugtXNvb5sxC8YcZ45rHP7b9y5sfGPy1a244lP29N9r9M8v/DeAQ7x/yqLTkiTdyoLzt2nuh6vpeP+rqM3yk+NueeEbGdbYVhnh6J4e6NwTCDewQhhgLAB6vfvMI0h5UL4Yg9zq5gwdIhJBYZ/XIBFhsV4RoJD9kH37trnHTNiLSpENnW+tYqoTewEpvdUiqwQQd8llY43e2ac2hgtX9dFzvWpd7urGqvQ1XZXim6AQUE3jc3sBx6mMxhaS5lWv4hrecGnx4VilXAbunUxsrfm63s0pemu7jBRoWOiSaAcpdR2AwHoAFHO2euL9JHnMh+70VAeuLBhG6wkY2uRDWgfib2iUAKEJq2k++a4Ug2ZULLW5M=
install:
- mkdir -p "$TRAVIS_BUILD_DIR/gosrc"
- mkdir -p "$TRAVIS_BUILD_DIR/static"
- go get -u -v github.com/spf13/hugo
- go get -v github.com/spf13/hugo
script: ./scripts/deploy.sh
deploy:
  provider: s3
  access_key_id: AKIAICEXZH3PUZE3V2OA
  secret_access_key:
    secure: nr2DyEdmhTPtzZf0jjzGomXOGjd82aWw5nhB65uVvQ+dJIG9hMYEgCIRipet15k+nuVVMqgqKeHqujuxb6NXwon7xRkbAfKP2qXSUVY+PnmVVf7PCgcWHMchSalYra3eGVRcGYpjYMDM9ofjLjV54+nvChDwwyD6DvKR3KkLJY+sbvz8WhlEgOMkmAQMZvQtOYZAWCC/q/EkCM75UT2fEL6T4l1c+jK3PyiPY2wRWhpKdpjEiyo07qHE/cwPvWNycGLCRI3ZncRSvJ2MUOdElZIGG13Xt2ezrJVfvRPnvv9IpGkMBXrk2ePTwiLV/pW88uXZwrH9cWAlORIYlJOu/jPgRzX1TEapBi5MwOzY0rxsC//bvslr4Wf08LRq4Q3vN8e2+9plaRPNRsvHUqucaT6pR3YLCEYcElOiih1IEOnbELxA+TRI1g7j50A+0BNVOABme2aZlE4snqqsbAu9Qajw7PcTliLaeY0MWCK6tYBErlMUnSnc3ud1pQ/d9RvhhRPCnKKG4oG337HyKZV1ATij8qNV+GLhgGp4betsj8WQTRQgg4nEXCvdDcg/w7fgOo+fKC0f4Yw7i19B/FeKtsXBtBiFF9RSGjEMn7T0sD8yoXU/5hvFxnnlNrh5X/tsyt7+8R85saK20VmUpmxrD89C5cPD2Ng0fOW+Q9ESHWw=
  region: sa-east-1
  bucket: blog.autoconexao.org.br
  skip_cleanup: true
  endpoint: blog.autoconexao.org.br.s3-website-sa-east-1.amazonaws.com
  local-dir: public
  on:
    repo: oikon/autoconexao
notifications:
  email:
    - tech@oikon.org.br
